### ISSUE TITLE
PrimeNG Dropdown test fails

### ISSUE THREAD

**Issue by pturchinetz** [dougnoel/sentinel#351]
There is a new redirect on the dropdown page that causes tests to fail:
https://www.primefaces.org/primeng-5-2-0-final-released/dropdown/

Instead, start at this URL: https://www.primefaces.org/primeng/
Click Compponents
Click Form (left side nav) -> Dropdown

**Comment by plmlkrz** [comment]
Navigation to https://www.primefaces.org/primeng/dropdown no longer redirects to https://www.primefaces.org/primeng-5-2-0-final-released/dropdown/ .  Reverted the changes back.
