### ISSUE TITLE
Relative path shortcut support - Windows automation

### ISSUE THREAD

**Issue by tyBouch** [dougnoel/sentinel#366]
Some Windows applications cannot have their install directory modified and install to a user's application, and local application, data folder in windows.

For testing Windows applications, we should support windows shortcuts such as %appdata% and %localappdata% for executable paths. Since these paths will change based on the current machine user this will remove any hard coded requirements for page objects.

**Comment by dougnoel** [comment]
I believe that the java library can resolve these. Have you tried it? I remember seeing something about the %User% directory working.

**Comment by tyBouch** [comment]
I have. Unfortunately it doesn't seem to apply to page objects for executables. We attempted to use %localappdata% where our executable installs, but it would not take.

I'm going to look into how we're grabbing that for winappdriver.

**Comment by tyBouch** [comment]
PR was already handled. Closing issue.
