### ISSUE TITLE
verifyColumnCellsAreUnique is doing a contains when doing the comparison

### ISSUE THREAD

**Issue by plmlkrz** [dougnoel/sentinel#547]
verifyColumnCellsAreUnique in Table.java is doing a contains when doing the comparison but since it is Unique, it should be doing an equals.
Ran across an issue where in the table the value was "sphinganine-1-phosphate" and "sphinganine".  The step failed because it thought that these were the same but they are unique.  It should be set to equal.  

for (String cell2 : column) {
					if (cell2.contains(cell)) {
						count++;
					}
Should read 
for (String cell2 : column) {
					if (cell2.equals(cell)) {
						count++;
					}

**Comment by tyBouch** [comment]
I believe the PR should be handled, but it was not attached. Reopen if this is not the case.
